ALTER TABLE products
ADD COLUMN created_by VARCHAR(255) NULL,
ADD COLUMN updated_by VARCHAR(255) NULL;

ALTER TABLE orders
ADD COLUMN created_by VARCHAR(255) NULL,
ADD COLUMN updated_by VARCHAR(255) NULL;