ALTER TABLE order_items
ADD COLUMN created_by VARCHAR(255) NULL,
ADD COLUMN updated_by VARCHAR(255) NULL;

ALTER TABLE users
ADD COLUMN created_by VARCHAR(255) NULL,
ADD COLUMN updated_by VARCHAR(255) NULL;